version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - '4600:27017'
    volumes:
      - /PCPartsTool-volume:/data/db
    restart: always

  price-scraper:
    image: 10.0.1.60:5000/pcpartstool-scraper:latest
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/pc-comparison-site
      - TZ=Asia/Kuala_Lumpur
    links:
      - db
    restart: always

  app:
    image: 10.0.1.60:5000/pcpartstool:latest
    depends_on:
      - db
    ports:
      - '3500:3000'
    environment:
      - MONGO_URL=mongodb://db:27017/pc-comparison-site
    links:
      - db
    restart: always
