version: '3.8'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3500:3000'
    restart: always

  db:
    image: mongodb
    ports:
      - '4600:27017'
    volumes:
      - /pc-comparison-site-volume:/data/db
    restart: always
